# Form implementation generated from reading ui file 'start_window.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(485, 312)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.create_room_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_room_btn.setGeometry(QtCore.QRect(310, 100, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.create_room_btn.setFont(font)
        self.create_room_btn.setObjectName("create_room_btn")
        self.join_room_btn = QtWidgets.QPushButton(self.centralwidget)
        self.join_room_btn.setGeometry(QtCore.QRect(310, 220, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.join_room_btn.setFont(font)
        self.join_room_btn.setObjectName("join_room_btn")
        self.join_room_line = QtWidgets.QLineEdit(self.centralwidget)
        self.join_room_line.setGeometry(QtCore.QRect(30, 160, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.join_room_line.setFont(font)
        self.join_room_line.setFrame(False)
        self.join_room_line.setObjectName("join_room_line")
        self.hidden_word_line = QtWidgets.QLineEdit(self.centralwidget)
        self.hidden_word_line.setGeometry(QtCore.QRect(30, 40, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.hidden_word_line.setFont(font)
        self.hidden_word_line.setMaxLength(5)
        self.hidden_word_line.setFrame(False)
        self.hidden_word_line.setObjectName("hidden_word_line")
        self.create_word_label = QtWidgets.QLabel(self.centralwidget)
        self.create_word_label.setEnabled(True)
        self.create_word_label.setGeometry(QtCore.QRect(30, 100, 271, 20))
        self.create_word_label.setObjectName("create_word_label")
        self.join_room_label = QtWidgets.QLabel(self.centralwidget)
        self.join_room_label.setEnabled(True)
        self.join_room_label.setGeometry(QtCore.QRect(30, 220, 271, 20))
        self.join_room_label.setObjectName("join_room_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.create_room_btn.setText(_translate("MainWindow", "Create room"))
        self.join_room_btn.setText(_translate("MainWindow", "Join room"))
        self.join_room_line.setPlaceholderText(_translate("MainWindow", "Input room number"))
        self.hidden_word_line.setPlaceholderText(_translate("MainWindow", "Input word (5 letter and rus)"))
        self.create_word_label.setText(_translate("MainWindow", "Word does\'t meet the conditions "))
        self.join_room_label.setText(_translate("MainWindow", "Room is full or does\'t exist"))
